# Generated by Django 4.2.7 on 2023-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='genre',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Sport', 'Sport')], max_length=100),
        ),
    ]
