# Generated by Django 4.2.7 on 2023-11-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_filmmodel_options_alter_filmmodel_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Укажите название авто'),
        ),
    ]
